### ISSUE TITLE
文档核心翻译任务认领

### ISSUE THREAD

**Issue by QC-L** [docschina/webpack.js.org#752]
翻译前，请仔细阅读 [中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)。

## 任务认领说明

> 注意：一次尽量只认领一篇，给其他小伙伴留些机会~

从 Todo List 中选取未被人领取过的文章：

未被领取过：

<img src="https://user-images.githubusercontent.com/40483898/117529389-e221eb00-b009-11eb-8940-8dc87cceeac8.png" height="50">

领取过：

<img src="https://user-images.githubusercontent.com/40483898/117529392-ec43e980-b009-11eb-9262-c9b3197b59cb.png" height="50">

领取过，已完成：

<img src="https://user-images.githubusercontent.com/40483898/117529397-ef3eda00-b009-11eb-927b-d737a338f932.png" height="50">

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  To v4 from v3 | @QC-L  | 2020.06.14 - 2020.06.17
```

示例效果：

| Section | Title         | 译者  | 完成时间                |
| ------- | ------------- | ----- | ----------------------- |
| Migrate | To v4 from v3 | @QC-L | 2020.06.14 - 2020.06.17 |

## 任务认领列表

Todo List:

Migrate

* [x] [To v5 from v4](https://github.com/docschina/webpack.js.org/blob/cn/src/content/migrate/5.md) （@QC-L）
* [x] [To v4 from v3](https://github.com/docschina/webpack.js.org/blob/cn/src/content/migrate/4.md) （@Catherine001li） #772
* [x] [To v2 or v3 from v1](https://github.com/docschina/webpack.js.org/blob/cn/src/content/migrate/3.md) （@miazhuce） #781
* [x] [index](https://github.com/docschina/webpack.js.org/blob/cn/src/content/migrate/index.md) (@jacob-lcs ) #956

Configuration

* [x] [index](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/index.mdx) (@dear-lizhihua) #822
* [x] [Output](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/output.md) （@navigatorOpera） #776
* [x] [Mode](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/mode.md) （@aa875982361） #763
* [x] [Entry and Context](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/entry-context.md) （@jungor） #757
* [x] [Configuration Types](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/configuration-types.md) （@doflamin） #871
* [x] [Configuration Languages](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/configuration-languages.md) （@NealST） #786
* [x] [DevServer](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/dev-server.md) （@jerexyz） #773
* [x] [DevTool](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/devtool.md) （@weiyuan0609） #761
* [x] [Experiments](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/experiments.md) （@lcxfs1991）
* [x] [Externals](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/externals.mdx) （@lcxfs1991）
* [x] [Module](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/module.mdx) （@chengxi.li）
* [x] [Node](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/node.md) （@QC-L）
* [x] [Optimization](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/optimization.md) （@chengxi.li）
* [x] [Other options](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/other-options.md) （@lcxfs1991）
* [x] [Performance](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/performance.md) （@lcxfs1991）
* [x] [Plugins](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/plugins.md) （@chengxi.li）
* [x] [Resolve](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/resolve.mdx) （@chengxi.li）
* [x] [Stats](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/stats.md) （@lcxfs1991）
* [x] [Targets](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/target.md) （@chengxi.li）
* [x] [Watch](https://github.com/docschina/webpack.js.org/blob/cn/src/content/configuration/watch.mdx) （@lcxfs1991）

Guides

* [ ] [Package exports](https://github.com/docschina/webpack.js.org/blob/cn/src/content/guides/package-exports.md)
* [x] [Web Workers](https://github.com/docschina/webpack.js.org/blob/cn/src/content/guides/web-workers.mdx) (@KimYangOfCat) #1075 

API

* [x] [Command Line Interface](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/cli.md) （@Fonkie） #787
* [x] [Compilation Object](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/compilation-object.md) （@jacob-lcs） #764
* [x] [Hot Module Replacement](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/hot-module-replacement.md) （@Geekhyt） #756
* [x] [API](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/index.md) （@Xeonice） #760
* [x] [Loader Interface](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/loaders.md) （@Aastasia） #755
* [x] [Logger Interface](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/logging.md) （@wangjq4214） #754
* [x] [Node Interface](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/node.mdx) （@ssszp） #768
* [x] [Module Methods](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/module-methods.md) （@kingzez） #766
* [x] [Module Variables](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/module-variables.md) （@carlz812） #775
* [x] [Plugin API](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/plugins.md) （@chenzesam） #759
* [x] [Resolvers](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/resolvers.md) （@pampang） #778
* [ ] [Stats Data](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/stats.mdx)（@Usualminds）
* [x] [Compilation hooks](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/compilation-hooks.mdx)（@dear-lizhihua）
* [x] [Compiler hooks](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/compiler-hooks.md)（@dear-lizhihua）
* [x] [ContextModuleFactory Hooks](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/contextmodulefactory-hooks.md) (@KimYangOfCat) #1077
* [x] [NormalModuleFactory Hooks](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/normalmodulefactory-hooks.md) (@KimYangOfCat) #1081
* [x] [JavascriptParser Hooks](https://github.com/docschina/webpack.js.org/blob/cn/src/content/api/parser.md)（@chengxi.li）

其它

* [x] [Branding](https://github.com/docschina/webpack.js.org/blob/cn/src/content/branding.md) (@helianthuswhite) #774
* [x] [Comparision](https://github.com/docschina/webpack.js.org/blob/cn/src/content/comparison.md) （@mercurywang） #790
* [x] [Glossary](https://github.com/docschina/webpack.js.org/blob/cn/src/content/glossary.md) (@daxiaoxiaodejia) #782
* [x] [License](https://github.com/docschina/webpack.js.org/blob/cn/src/content/license.md) （@GSZS） #771
* [x] [index](https://github.com/docschina/webpack.js.org/blob/cn/src/content/index.md) （@QC-L）
* [x] [vote](https://github.com/docschina/webpack.js.org/blob/cn/src/content/vote.md)

Plugin 以及 Loaders 相关翻译领取，请参见 #753

**Comment by Fonkie** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API  |  Command Line Interface | @Fonkie  | 2020.06.14 - 2020.06.21

**Comment by chenzesam** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |  Plugin API | @chenzesam  | 2020.06.15 - 2020.06.21

**Comment by kingzez** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |  Module Methods | @kingzez  | 2020.06.15 - 2020.06.20

**Comment by jacob-lcs** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |  Compilation Object | @jacob-lcs  | 2020.06.15 - 2020.06.21

**Comment by Aastasia** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | Loader Interface | @Aastasia | 2020.06.15 - 2020.06.21

**Comment by Geekhyt** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |   Loader Interface | @Geekhyt | 2020.06.15 - 2020.06.21

**Comment by wangjq4214** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | Logger Interface | @wangjq4214  | 2020.06.14 - 2020.06.21

**Comment by Geekhyt** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  Hot Module Replacement | @Geekhyt  | 2020.06.15 - 2020.06.21

**Comment by carlz812** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | Module Variables ｜ @carlz812 | 2020.06.15 - 2020.06.21

**Comment by ssszp** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API|  Node Interface | @ssszp  | 2020.06.15 - 2020.06.21

**Comment by pampang** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  Resolvers | @pampang  | 2020.06.15 - 2020.06.21

**Comment by devtalker** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | Stats Data | @yancongwen  | 2020.06.15 - 2020.06.17

申请时间已过期，此文章释放

**Comment by yancongwen** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |  API | @yancongwen   | 2020.06.15 - 2020.06.21

**Comment by Catherine001li** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate | To v4  from v3 | @aiya495 | 2020.06.15 - 2020.06.21

**Comment by jungor** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Entry and Context | @jungor | 2020.06.15 - 2020.06.21

**Comment by jerexyz** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  DevServer| @jerexyz  | 2020.06.16 - 2020.06.12

**Comment by JarryChung** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration | DevServer | @JarryChung | 2020.06.16 - 2020.06.21

**Comment by navigatorOpera** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Output | @navigatorOpera  | 2020.06.16 - 2020.06.21

**Comment by doflamin** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Configuration Types | @doflamin  | 2020.06.16 - 2020.06.20

**Comment by weiyuan0609** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  DevTool | @weiyuan0609  | 2020.06.16 - 2020.06.21

**Comment by Xeonice** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | API | @Xeonice | 2020.06.16 - 2020.06.21

**Comment by aa875982361** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Mode | @aa875982361 | 2020.06.15 - 2020.06.19

**Comment by NealST** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Configuration Languages | @NealST(墨筝)  | 2020.06.15 - 2020.06.19

**Comment by BiuBiuHu** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  Configuration Languages | @BiuBiu_Hu  | 2020.06.15 - 2020.06.19

**Comment by miazhuce** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Migrate |  To v2 or v3 from v1 | @mia  | 2020.06.16 - 2020.06.22

**Comment by dear-lizhihua** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Configuration |  index | @dear-lizhihua  | 2020.06.16 - 2020.06.22

**Comment by daxiaoxiaodejia** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
其他 |  Glossary | @daxiaoxiaodejia  | 2020.06.16 - 2020.06.21

**Comment by helianthuswhite** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
其他 |  Branding | @helianthuswhite | 2020.06.16 - 2020.06.22

**Comment by GSZS** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
其他 |  License |  @GSZS  | 2020.06.19 - 2020.06.25

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
其他 |  Comparison | @mercurywang  | 2020.06.29 - 2020.07.02

**Comment by blesstosam** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
概念 |  Module Federation | @blesstosam  | 2020.10.22 - 2020.10.22

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guides | Web Workers | @KimYangOfCat | 2021.04.30-2021.05.01

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | ContextModuleFactory Hooks | @KimYangOfCat | 2021.04.30-2021.05.02

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API | NormalModuleFactory Hooks | @KimYangOfCat | 2021.05.02-2021.05.04

**Comment by Usualminds** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
API |  Stats Data | @Usualminds | 2021.06.17 - 2021.06.19

**Comment by novlan1** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guides |  Package exports | @novlan1  | 2021.12.16 - 2021.12.21

**Comment by Catherine001li** [comment]
您的来件已收到，谢谢!

**Comment by Catherine001li** [comment]
您的来件已收到，谢谢!

**Comment by Erchiusx** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Guides |  Package exports | @Erchiusx | 2024.9.29-2024.10.2

**Comment by Catherine001li** [comment]
您的来件已收到，谢谢!
