### ISSUE TITLE
Plugin 及 Loader 相关任务认领

### ISSUE THREAD

**Issue by QC-L** [docschina/webpack.js.org#753]
翻译前，请仔细阅读 [中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97)。

## 任务认领说明

> 注意：一次尽量只认领一篇，给其他小伙伴留些机会~

从 Todo List 中选取未被人领取过的文章：

未被领取过：

<img src="https://user-images.githubusercontent.com/40483898/117529389-e221eb00-b009-11eb-8940-8dc87cceeac8.png" height="50">

领取过：

<img src="https://user-images.githubusercontent.com/40483898/117529392-ec43e980-b009-11eb-9262-c9b3197b59cb.png" height="50">

领取过，已完成：

<img src="https://user-images.githubusercontent.com/40483898/117529397-ef3eda00-b009-11eb-927b-d737a338f932.png" height="50">

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  worker-loader | @QC-L  | 2020.06.14 - 2020.06.17
```

示例效果：

Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader |  worker-loader | @QC-L  | 2020.06.14 - 2020.06.17

## 任务认领列表

Todo List:

Loader

- [x] [babel-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/babel-loader.md) （@flytam） #770 
~- [x] [bundle-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/bundle-loader.md)~ （@mercurywang） #783
- [x] [cache-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/cache-loader.md) （@mercurywang） #785 
- [x] [coffee-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/coffee-loader.md) （@mercurywang）#792
- [x] [css-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/css-loader.md) （@Jacksonlike）#890
- [x] [eslint-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/eslint-loader.md) （@Xeonice） #791 
- [x] [exports-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/exports-loader.md)(@jacob-lcs) #933 
- [x] [expose-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/expose-loader.md)（@wangyiman）#972
- [ ] [extract-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/extract-loader.md)（@YoungCC2）
- [x] [file-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/file-loader.md) （@jacob-lcs）
- [x] [html-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/html-loader.md) （@92hackers） #833 
- [x] [imports-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/imports-loader.md)（@jacob-lcs）
- [x] [index](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/index.md) （@92hackers）#835
- [x] [istanbul-instrumenter-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/istanbul-instrumenter-loader.md)（@LJCandyCrush）
- [x] [less-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/less-loader.md) （@phobal） #806 
- [x] [mocha-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/mocha-loader.md)（@applegz）#966
- [x] [node-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/node-loader.md)（@jacob-lcs）#965
- [x] [null-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/null-loader.md)（@KimYangOfCat）
- [ ] [polymer-webpack-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/polymer-webpack-loader.md)
- [x] [postcss-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/postcss-loader.md)（@wangjq4214）#890
- [x] [raw-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/raw-loader.md)
- [x] [remark-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/remark-loader.md)
- [x] [sass-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/sass-loader.md) （@wangjq4214） #788 
- [x] [source-map-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/source-map-loader.md) （@mercurywang） #797 
- [x] [style-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/style-loader.md) （@lmhcoding） #799 
- [x] [stylus-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/stylus-loader.md) (@Usualminds)
- [x] [svg-inline-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/svg-inline-loader.md)
- [x] [thread-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/thread-loader.md) （@weiyuan0609）#818
~- [ ] [transform-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/transform-loader.md)~
- [x] [url-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/url-loader.md)
- [ ] [val-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/val-loader.md)
- [x] [worker-loader](https://github.com/docschina/webpack.js.org/tree/cn/src/content/loaders/worker-loader.md) （@jacob-lcs） #779 

Plugin

- [x] [dll-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/dll-plugin.md) （@weiyuan0609） #795 
- [x] [automatic-prefetch-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/automatic-prefetch-plugin.md)
- [x] [babel-minify-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/babel-minify-webpack-plugin.md)
- [x] [banner-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/banner-plugin.md)（@watonyweng） #1280
- [ ] [closure-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/closure-webpack-plugin.md)
- [ ] [commons-chunk-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/commons-chunk-plugin.md)
- [ ] [compression-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/compression-webpack-plugin.md)
- [ ] [context-exclusion-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/context-exclusion-plugin.md)
- [ ] [context-replacement-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/context-replacement-plugin.md)
- [ ] [copy-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/copy-webpack-plugin.md)
- [x] [define-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/define-plugin.md) （@Maxim-HSP）#805
- [ ] [environment-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/environment-plugin.md)
- [x] [eval-source-map-dev-tool-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/eval-source-map-dev-tool-plugin.md)（@niubaobaozsy）#863
- [ ] [extract-text-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/extract-text-webpack-plugin.md)
- [ ] [hashed-module-ids-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/hashed-module-ids-plugin.md)
- [x] [hot-module-replacement-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/hot-module-replacement-plugin.md) （@navigatorOpera） #802 
- [x] [html-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/html-webpack-plugin.md)(@jacob-lcs) #945
- [x] [i18n-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/i18n-webpack-plugin.md) （@NealST） #793 
- [ ] [ignore-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/ignore-plugin.md)
- [ ] [index](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/index.md)
- [ ] [internal-plugins](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/internal-plugins.md)
- [ ] [limit-chunk-count-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/limit-chunk-count-plugin.md)
- [ ] [min-chunk-size-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/min-chunk-size-plugin.md)
- [x] [mini-css-extract-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/mini-css-extract-plugin.md) （@wangjq4214） #824 
- [ ] [module-concatenation-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/module-concatenation-plugin.md)
- [ ] [normal-module-replacement-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/normal-module-replacement-plugin.md)
- [ ] [npm-install-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/npm-install-webpack-plugin.md)
- [ ] [prefetch-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/prefetch-plugin.md)
- [ ] [profiling-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/profiling-plugin.md)
- [ ] [progress-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/progress-plugin.md)
- [ ] [provide-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/provide-plugin.md)
- [x] [source-map-dev-tool-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/source-map-dev-tool-plugin.md)（@jacob-lcs）#963
- [x] [split-chunks-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/split-chunks-plugin.md) (@weiyuan0809) #854
- [x] [stylelint-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/stylelint-webpack-plugin.md)（@fine-bot）#969
- [x] [terser-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/terser-webpack-plugin.md)
- [x] [uglifyjs-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/uglifyjs-webpack-plugin.md) （@jefferyE） #780 
- [ ] [watch-ignore-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/watch-ignore-plugin.md)
- [ ] [zopfli-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/zopfli-webpack-plugin.md)
- [x] [css-minimizer-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/css-minimizer-webpack-plugin.md)（@fine-bot）#974
- [ ] [eslint-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/eslint-webpack-plugin.md)
- [ ] [image-minimizer-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/image-minimizer-webpack-plugin.md)
- [ ] [json-minimizer-webpack-plugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/json-minimizer-webpack-plugin.md)
- [ ] [NoEmitOnErrorsPlugin](https://github.com/docschina/webpack.js.org/tree/cn/src/content/plugins/NoEmitOnErrorsPlugin.md)

**Comment by weiyuan0609** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugins | dll-plugin | @weiyuan0609 | 2020.06.19 - 2020.06.29

**Comment by flytam** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |   babel-loader | @flytam  | 2020.06.19 - 2020.06.29

**Comment by NealST** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  i18n-webpack-plugin | @NealST  | 2020.06.19 - 2020.06.29

**Comment by wangjq4214** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  sass-loader | @wangjq4214  | 2020.06.19 - 2020.06.29

**Comment by jacob-lcs** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  worker-loader | @jacob-lcs  | 2020.06.21 - 2020.06.27

**Comment by navigatorOpera** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | hot-module-replacement-plugin | @navigatorOpera | 2020.06.22 - 2020.06.25

**Comment by jefferyE** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | uglifyjs-webpack-plugin | @jefferyE | 2020.06.23 - 2020.06.27

**Comment by jefferyE** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | uglifyjs-webpack-plugin | @jefferyE | 2020.06.23 - 2020.06.27

**Comment by Xeonice** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  eslint-loader | @Xeonice  | 2020.06.23 - 2020.06.27

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader | bundle-loader | @mercurywang  | 2020.06.24 - 2020.06.27

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  cache-loader | @mercurywang   | 2020.06.25 - 2020.06.27

**Comment by lmhcoding** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  style-loader | @lmhcoding  | 2020.06.29 - 2020.07.01

**Comment by beetaa** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  css-loader | @beetaa | 2020.06.29 - 2020.07.02

**Comment by phobal** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | less-loader | @phobal | 2020.07.01 - 2020.07.10

**Comment by Maxim-HSP** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  define-plugin | @Maxim3244   | 2020.07.01 - 2020.07.10

**Comment by daxiaoxiaodejia** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader | file-loader | @daxiaoxiaodejia  | 2020.07.01 - 2020.07.06

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  coffee-loader | @mercurywang   | 2020.06.29 - 2020.07.02

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  source-map-loader | @mercurywang   | 2020.06.29 - 2020.07.02

**Comment by beetaa** [comment]
提交的 pr 几天都没人管，组织太松散了，css-loader 我退了。

**Comment by mercurywang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  terser-webpack-plugin | @mercurywang   | 2020.07.05 - 2020.07.08

**Comment by Jacksonlike** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  css-loader |  @Jacksonlike  | 2020.07.06 - 2020.07.12

**Comment by weiyuan0609** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  thread-loader | @weiyuan0609   | 2020.07.08 - 2020.07.14

**Comment by wangjq4214** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | mini-css-extract-plugin | @wangjq4214 | 2020.07.14 - 2020.07.21

**Comment by weiyuan0609** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  split-chunks-plugin | @weiyuan0609   | 2020.08.06 - 2020.08.13

**Comment by 92hackers** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  html-loader | @92hackers  | 2020.08-11 - 2020.08.14

**Comment by 92hackers** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  index  | @92hackers   | 2020.08.12-2020.08.14

**Comment by wangjq4214** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | postcss-loader | @wangjq4214 | 2020.10.01 - 2020.10.06

**Comment by 92hackers** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  terser-webpack-plugin | @92hackers  | 2020.08.17 - 2020.08.20

**Comment by 92hackers** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin | closure-webpack-plugin | @92hackers  | 2020.08-24 - 2020.08-27

**Comment by niubaobaozsy** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  eval-source-map-dev-tool-plugin | @niubaobaozsy | 2020.09.28 - 2020.10,11

**Comment by daxiaoxiaodejia** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  json5-loader | @daxiaoxiaodejia   | 2020.12.22 - 2020.12.30

**Comment by daxiaoxiaodejia** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  node-loader | @daxiaoxiaodejia   | 2020.12.23 - 2020.12.30

**Comment by jacob-lcs** [comment]
|Section|Title|译者|完成时间|
|--|--|--|--|
| Loader|exports-loader|@jacob-lcs|2021.01.13 - 2021.01.20|

**Comment by jacob-lcs** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | html-webpack-plugin | @jacob-lcs | 2021.01.22 - 2021.01.30

**Comment by fine405** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  stylelint-webpack-plugin | @fine-bot  | 2021.02.11 - 2021.02.13

**Comment by wangyiman** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader |   expose-loader | @wangyiman | 2021.02.11 - 2021.02.16

**Comment by jacob-lcs** [comment]
> Section	Title	译者	完成时间
> Loader	svg-inline-loader	@wangyiman	2021.02.11 - 2021.02.16
> Loader	expose-loader	@wangyiman	2021.02.11 - 2021.02.16
> Loader	extract-loader	@wangyiman	2021.02.11 - 2021.02.16

三篇文档放在三个分支哈~

**Comment by wangyiman** [comment]
ok

**Comment by applegz** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  mocha-loader | @applegz  | 2021.02.11 - 2020.02.18

**Comment by wangyiman** [comment]
@jacob-lcs 可以把后两篇去掉么，之前没仔细看文档

**Comment by fine405** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin| css-minimizer-webpack-plugin | @fine-bot   | 2021.02.14 - 2021.02.17

**Comment by YoungCC2** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  extract-loader  | [@YoungCC2](https://github.com/YoungCC2)  | 2021.02.15 - 2020.02.17

**Comment by LJCandyCrush** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | istanbul-instrumenter-loader | @LJCandyCrush | 2021.02.28 - 2021.03.07

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | null-loader | @KimYangOfCat | 2021.04.13-2021.04.17

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | svg-inline-loader | @KimYangOfCat | 2021.04.15-2021.04.22

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Loader | raw-loader | @KimYangOfCat | 2021.04.25-2021.04.27

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | babel-minify-webpack-plugin | @KimYangOfCat | 2021.04.28-2021.05.01

**Comment by Usualminds** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  stylus-loader | @Usualminds  | 2021.06.16 - 2021.06.18

**Comment by fikyair** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  automatic-prefetch-plugin | @fikyair |2021.07.04 - 2021.07.06

**Comment by fikyair** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Loader |  remark-loader | @fikyair   | 2021.07.13 - 2021.07.15

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| Plugin | banner-plugin | @watonyweng | 2021.08.26 - 2021.08.28 | #1280 |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| Plugin | progress-plugin | @watonyweng | 2021.08.29 - 2021.08.31 | - |

**Comment by jsbugwang** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  eslint-webpack-plugin | @jsbugwang  | 2021.09.27 - 2021.09.28

**Comment by novlan1** [comment]
Section | Title | 译者 | 完成时间 
-- | -- | -- | -- 
Plugin |  commons-chunk-plugin | @novlan1  | 2021.12.29 - 2021.12.30

**Comment by wangjq4214** [comment]
Section | Title | 译者 | 完成时间
-- | -- | -- | --
Plugin | commons-chunk-plugin | @wangjq4214 | 2021.01.07 - 2020.01.09

**Comment by Otto-J** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
Plugin | module-federation-plugin| @otto-j | 2022-08-18 - 2022-08-20 | --
